---
- hosts: "{{hosts}}"
  tasks:
    - name: setup pg 11
      shell: |
        rpm -Uvh https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm

        yum install -y postgresql11  postgresql11-server python-pip

    - name: initdb
      shell: |
        /usr/pgsql-11/bin/postgresql-11-setup initdb
      ignore_errors: true

    - name: setup service
      shell: |
        systemctl enable postgresql-11.service
        systemctl start postgresql-11.service

- hosts: "{{hosts}}"
  tasks:
    - name: replace peer with trust in postgresql login (temporary)
      lineinfile:
        dest: /var/lib/pgsql/11/data/pg_hba.conf
        regexp: 'local   all             all                                     peer'
        line: local   all             all                                     trust


    - name: restart postgresql service
      service:
        name: postgresql-11
        state: restarted

    # psycopg2 needed for user, db creation
    - pip:
        name: psycopg2-binary

    - name: create postgresql user
      postgresql_user:
        user: "zabbix"
        password: "zabbix"
        role_attr_flags: "CREATEDB,NOSUPERUSER"
      become: true
      become_user: postgres

    - name: create postgresql db
      postgresql_db:
        name: "zabbix"
        state: present
      become: true
      become_user: postgres

- hosts: "{{hosts}}"
  tasks:
    - name: Import initial schema and data
      shell: |
        zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix
        expect"Enter zabbix password:"
        send"{{zabbix}}\n"
