---
- name: Set SELinux to permissive mode
  hosts: "{{hosts}}"
  become: true

  tasks:
  - name: Set SELinux to permissive mode
    shel: setenforce 0 && sudo sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    ignore_error: true

- name: install zabbix
  hosts: "{{hosts}}"
  become: true
 
  tasks:
    - name: install Zabbix repository
      yum:
        name: " rpm -Uvh https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64\
          /zabbix-release-4.4-1.el7.noarch.rpm"
        state: present

    - name: Install Zabbix server, frontend, agent
      yum:
        name: '{{items}}'
        state: present
        with_items:
          - zabbix-server-pgsql
          -	zabbix-web-pgsql
          - zabbix-agent
          -	httpd
          -	php-pgsql
          - php-ldap
          - php-bcmath
          - php-mbstring
          - php-gd
          - php-xml
          - php-mcrypt

- name: configure php file
  hosts: "{{hosts}}"
  become: true

  tasks:
    - name: change php.ini file to time zone
      lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '^# php_value date.timezone Europe/Riga'
        line: php_value date.timezone Africa/Cairo
      notify:
         - restart httpd

    - name: Configure the database for Zabbix server
      lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '^#DBPassword='
        line: DBPassword=zabbix

    - name: configure zabbix-agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^#ListenPort='
        line: ListenPort=10050

- name: Configure firewall
  hosts: "{{ hosts }}"
  become: true

  tasks:
    - name: enable service in firewall
      firewalled:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - httpd
        - https

    - name:
      firewalled:
        port: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - 80/tcp
        - 10050/tcp
        - 10051/tcp

- name: Configure firewall
  hosts: "{{ hosts }}"
  become: true	

 handlers:
     - name: restart httpd , zabbix-server , zabbix-agent
       service:
         name: "{{ item }}"
         state: restarted
       loop:
         - httpd
         - zabbix-server
         - zabbix-agent
