---
- name: Set SELinux to permissive mode
  hosts: "{{ hosts }}"
  become: true

  tasks:
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

- name: repo
  hosts: "{{hosts}}"

  tasks:
    - name: install Zabbix repository
      yum:
        name: "https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64\
          /zabbix-release-4.4-1.el7.noarch.rpm"

    - name: Install Zabbix server, frontend, agent , php
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-pgsql
        - zabbix-web-pgsql
        - zabbix-agent
        - httpd
        - php-pgsql
        - php-ldap
        - php-bcmath
        - php-mbstring
        - php-gd
        - php-xml
        - php-mcrypt

- name: start all
  hosts: "{{hosts}}"

  tasks:
    - name: start all
      service:
        name: "{{item}}"
        state: started
      loop:
        - httpd
        - zabbix-server
        - zabbix-agent

- name: configure php file
  hosts: "{{ hosts }}"

  tasks:
    - name: change php.ini file to time zone
      lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '^        # php_value date.timezone Europe/Riga'
        line: '        php_value date.timezone Africa/Cairo'

    - name: Configure the database for Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: DBPassword=zabbix

    - name: change data base host
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBHost=localhost'
        line: DBHost=localhost

    - name: configure zabbix-agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^#ListenPort='
        line: ListenPort=10050

- name: Configure firewall
  hosts: "{{ hosts }}"

  tasks:
    - name: enable service in firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - http
        - https

    - name: enable ports in firewall
      firewalld:
        port: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - 10050/tcp
        - 10051/tcp

- name: Configure systemd to all
  hosts: "{{ hosts }}"

  tasks:
    - name: restart httpd , zabbix-server , zabbix-agent
      service:
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop:
        - httpd
        - zabbix-server
        - zabbix-agent
